### ISSUE TITLE
Please, consider scaling image resolution in the next version of Unified-IO 

### ISSUE THREAD

**Issue by codonna9** [allenai/unified-io-2#2]
Thank you very much for releasing the paper, code and model. However, the resolutions of image input and image history (384x384 and 224x224) are very limited for real world vision tasks where we mostly use HD or full HD resolution. If possible, please consider using higher image resolution for the next version of Unified-IO

**Comment by chrisc36** [comment]
I agree that that can be a limitation, I think ideally the model should be able to handle variable-resolution images as input. We settled on those resolutions since it was enough for the tasks we were interested in and higher resolutions would increase the complexity and computational cost of the model.
